name: saifi_app
description: Saifi summer activities app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter

  # أيقونات
  cupertino_icons: ^1.0.2

  # فتح روابط خارجية
  url_launcher: ^6.2.5

  # HTTP للـ API
  http: ^1.6.0

  # تشفير (SHA-256)
  crypto: ^3.0.3
  
  # تخزين محلي
  shared_preferences: ^2.2.2

  # الخرائط والموقع
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_maps_flutter: ^2.14.0
  permission_handler: ^12.0.1

  # أنيميشن
  lottie: ^3.3.2

  # Dialogflow / Google Auth
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/font/RobotoMono-VariableFont_wght.ttf

  assets:
    - assets/logo.png
    - assets/home.png
    - assets/parentReg.png
    - assets/saifibot.json
